# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BrayCurtis <- function() {
    .Call(`_somKernels_BrayCurtis`)
}

cosine <- function() {
    .Call(`_somKernels_cosine`)
}

dice <- function() {
    .Call(`_somKernels_dice`)
}

jaccard <- function() {
    .Call(`_somKernels_jaccard`)
}

smc <- function() {
    .Call(`_somKernels_smc`)
}

