# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate additive symmetric distance
#'
#' A SOM kernel pointer used internally by the kohonen package functions
#' `som()` and `supersom()`.
#' @export
NULL

additive_symm <- function() {
    .Call(`_somKernels_additive_symm`)
}

BrayCurtis <- function() {
    .Call(`_somKernels_BrayCurtis`)
}

bhattacharyya <- function() {
    .Call(`_somKernels_bhattacharyya`)
}

canberra <- function() {
    .Call(`_somKernels_canberra`)
}

chebyshev <- function() {
    .Call(`_somKernels_chebyshev`)
}

clark <- function() {
    .Call(`_somKernels_clark`)
}

cosine <- function() {
    .Call(`_somKernels_cosine`)
}

czekanowski <- function() {
    .Call(`_somKernels_czekanowski`)
}

dice <- function() {
    .Call(`_somKernels_dice`)
}

divergence <- function() {
    .Call(`_somKernels_divergence`)
}

fidelity <- function() {
    .Call(`_somKernels_fidelity`)
}

harmonic_mean <- function() {
    .Call(`_somKernels_harmonic_mean`)
}

hassebrook <- function() {
    .Call(`_somKernels_hassebrook`)
}

hellinger <- function() {
    .Call(`_somKernels_hellinger`)
}

inner_product <- function() {
    .Call(`_somKernels_inner_product`)
}

intersection <- function() {
    .Call(`_somKernels_intersection`)
}

jaccard <- function() {
    .Call(`_somKernels_jaccard`)
}

jeffreys <- function() {
    .Call(`_somKernels_jeffreys`)
}

jensen_difference <- function() {
    .Call(`_somKernels_jensen_difference`)
}

k_divergence <- function() {
    .Call(`_somKernels_k_divergence`)
}

kulczynski_d <- function() {
    .Call(`_somKernels_kulczynski_d`)
}

lorentzian <- function() {
    .Call(`_somKernels_lorentzian`)
}

matusita <- function() {
    .Call(`_somKernels_matusita`)
}

motyka <- function() {
    .Call(`_somKernels_motyka`)
}

neyman <- function() {
    .Call(`_somKernels_neyman`)
}

pearson <- function() {
    .Call(`_somKernels_pearson`)
}

prob_symm <- function() {
    .Call(`_somKernels_prob_symm`)
}

ruzicka <- function() {
    .Call(`_somKernels_ruzicka`)
}

smc <- function() {
    .Call(`_somKernels_smc`)
}

soergel <- function() {
    .Call(`_somKernels_soergel`)
}

squared_chi <- function() {
    .Call(`_somKernels_squared_chi`)
}

squared_chord <- function() {
    .Call(`_somKernels_squared_chord`)
}

squared_euclidean <- function() {
    .Call(`_somKernels_squared_euclidean`)
}

taneja <- function() {
    .Call(`_somKernels_taneja`)
}

topsoe <- function() {
    .Call(`_somKernels_topsoe`)
}

wavehedges <- function() {
    .Call(`_somKernels_wavehedges`)
}

